R:/Research_Data/SimulationRuns/rSHAPE_validation/valid_rSHAPE_2_6/SHAPE_submit_valid_rSHAPE_2_6.sh
R:/Research_Data/SimulationRuns/rSHAPE_validation/valid_rSHAPE_3_6/SHAPE_submit_valid_rSHAPE_3_6.sh
R:/Research_Data/SimulationRuns/rSHAPE_validation/valid_rSHAPE_4_6/SHAPE_submit_valid_rSHAPE_4_6.sh
R:/Research_Data/SimulationRuns/rSHAPE_validation/valid_rSHAPE_5_6/SHAPE_submit_valid_rSHAPE_5_6.sh
